# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

#  - name: Unterhaltungen
#    url: /#talks
#    weight: 12

#  - name: Bildung
#    url: teaching/
#    weight: 40

#  - name: Angebotene Dienstleistungen
#    url: projects/
#    weight: 30

main:
  - name: Wer ist Hunor Becsi?
    url: /
    weight: 10
  - name: Ausgew√§hlte Blog-Artikel
    url: /#papers
    weight: 11
  - name: Alle Blog-Artikel
    url: /#news
    weight: 13
  - name: Berufserfahrung
    url: experience/
    weight: 20


